### ISSUE TITLE
A couple of issues: 

### ISSUE THREAD

**Issue by YounesBensoudaMourri** [alontalmor/MultiQA#2]
from models.multiqa_reader_old import *
1) is not working because the file is not there. 

2) allennlp.common.checks.ConfigurationError: 'Cannot register multiqa_reader as DatasetReader; name already in use for MultiQAReader' 

3) The virtual environment set up also does not work.

**Comment by alontalmor** [comment]
Hi, 

Fixed 1 and 2.

Can you please elaborate on why the venv setup does not work for you?
