### ISSUE TITLE
Error in Building dataset.

### ISSUE THREAD

**Issue by rsanjaykamath** [alontalmor/MultiQA#3]
Hello, 

I tried to build the dataset as given in the readme file.  

Using this command: `python build_dataset.py --dataset_name HotpotQA --split train --output_file datasets/HotpotQA/ --n_processes 10
`

I get this error: 

> Traceback (most recent call last):
  File "build_dataset.py", line 100, in <module>
    main()
  File "build_dataset.py", line 28, in main
    preprocessor, args.sample_size, args.input_file)
  File "/people/sanjay/multiqa/datasets/multiqa_factory.py", line 13, in build_dataset
    contexts = dataset_class.build_contexts(preprocessor, split, sample_size, dataset_version, dataset_flavor, dataset_specific_props, input_file)
  File "/people/sanjay/multiqa/datasets/HotpotQA/hotpotqa.py", line 136, in build_contexts
    if 'original_context_order' in dataset_specific_props:
TypeError: argument of type 'NoneType' is not iterable

**Comment by alontalmor** [comment]
Thanks for that, i'll recreate this now.

**Comment by alontalmor** [comment]
Hi
I've fixed this bug, please pull and try to run again. 
If you have any additional problems or question i'd be happy to help.
Alon

**Comment by rsanjaykamath** [comment]
Ok the script runs fine now. 
Thanks for fixing it.
I'll run the code and if I find something I'll comment here or will close this issue by the end of the day. 

Thanks again, great work!
