### ISSUE TITLE
Question about `cannot_answer` chunks

### ISSUE THREAD

**Issue by Shayne13** [alontalmor/MultiQA#5]
Do you only support `cannot_answer` chunks during training for SQuAD 2.0 and other datasets that are scored on abstaining from answering the question? (As opposed to datasets that always have an answer somewhere in the context - though maybe not in every chunk.)

Was a little confused by the comment above this code in the reader:
https://github.com/alontalmor/MultiQA/blob/master/models/multiqa_reader.py#L380-L383

Thanks you for the clarification!

**Comment by alontalmor** [comment]
Thanks for the note, i will clarify the comment in the code. 
For now the cannot_answer is available only for datasets with cannot_answer such as SQuAD 2.0 and NaturalQuestions in the future.. (please make sure to enable cannot_answer in the config as well).

I am planning to add an option for negative examples (examples that do not contain an answer but are not marked by annotators as cannot_answer)  in other datasets in the future.
