### ISSUE TITLE
Error when building datasets

### ISSUE THREAD

**Issue by tuvuumass** [alontalmor/MultiQA#8]
Hello Alon,

I tried to build the dataset as in the README file.

`python build_dataset.py --dataset_name DROP --split train --output_file DROP.jsonl.gz --n_processes 10`

But I got this error:

```
Traceback (most recent call last):
  File "build_dataset.py", line 118, in <module>
    main()
  File "build_dataset.py", line 34, in main
    preprocessor, args.sample_size, args.max_contexts_in_file, args.custom_input_file):
  File "MultiQA/datasets/multiqa_factory.py", line 13, in build_dataset
    dataset_flavor, dataset_specific_props, sample_size, max_contexts_in_file, custom_input_file)
TypeError: __init__() takes 1 positional argument but 9 were given
```

**Comment by alontalmor** [comment]
Hi Tu, 

Yes, the DROP dataset is yet not fully converted (it also does not appear in the datasets available as described in the readme)

It will be fully added in the next few weeks. 
Thanks for understanding,
Alon
