### ISSUE TITLE
Can searchqa be converted to SQuAD format?

### ISSUE THREAD

**Issue by lixinsu** [alontalmor/MultiQA#9]
Maybe a stupid question, sorry. When trying to run the converting script to convert searchqa or triviaqa to SQuAD format, an error occurs. What is the reason? Is that forbidden?

**Comment by alontalmor** [comment]
This actually should work fine. Can you please send me the command you run?

**Comment by alontalmor** [comment]
Hey, 

I've added s3 links to most datasets in SQuAD2.0 format.

Please see the main README

Alon
